import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import React,{useState, useContext} from "react"
import { VotingContext } from '@/context/VotingContext'


export default function Home() {
	const [candidateInput, setCandidateInput] = useState({
		name: "",
		age: "",
		address: ""
	  })

	const [voterAddress, setVoterAddress] = useState("");
	const [winnerr, setWinnerr] = useState("")
	const {registerCandidates, whiteListAddress, startVoting, stopVoting, winner} = useContext(VotingContext)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
      <div className="flex justify-center items-center">
	       <div className="container mx-5 my-2  lg:px-20">

	    	<div className="w-full p-4 my-4 md:px-12 lg:w-9/12 lg:pl-20 lg:pr-40 mr-auto rounded-2xl shadow-2xl">
			<div className="flex">
				<h1 className="font-bold text-2xl">Register Candidate</h1>
			</div>
			<div className="grid grid-cols-1 gap-5 md:grid-cols-2 mt-2">

				<input 
				   className ="w-full bg-gray-100 text-gray-900 mt-2 p-3 rounded-lg focus:outline-none focus:shadow-outline"
				   type = "text"
                   title = "name"
                   placeholder = "Candidate Name"
                   onChange={(e) => setCandidateInput({...candidateInput, name: e.target.value})}  
				/>

				<input 
				   className="w-full bg-gray-100 text-gray-900 mt-2 p-3 rounded-lg focus:outline-none focus:shadow-outline"
				   type = "number"
                   title = "name"
                   placeholder = "Candidate Age"
                   onChange={(e) => setCandidateInput({...candidateInput, age: e.target.value})}  
			    />

				<input 
				   className="w-full bg-gray-100 text-gray-900 mt-2 p-3 rounded-lg focus:outline-none focus:shadow-outline"
				   type = "text"
                   title = "address"
                   placeholder = "Candidate Address"
                   onChange={(e) => setCandidateInput({...candidateInput, address: e.target.value})}  			
			    />
           </div>
				<div className="my-4 w-1/2 lg:w-1/4">
					<button 
					      className="uppercase text-sm font-bold tracking-wide bg-blue-900 text-gray-100 p-3 rounded-lg w-full 
                      focus:outline-none focus:shadow-outline"
					       onClick={registerCandidates}
					  
					>
                      Register Candidate
                    </button>
				</div>
			</div>

            <div className="w-full p-4 my-4 md:px-12 lg:w-9/12 lg:pl-20 lg:pr-40 mr-auto rounded-2xl shadow-2xl">
			   <div className="flex">
				  <h1 className="font-bold text-2xl">Register Voter</h1>
			   </div>
			<div className="grid grid-cols-1 gap-5 md:grid-cols-2 mt-2">
				<input 
				      className ="w-full bg-gray-100 text-gray-900 mt-2 p-3 rounded-lg focus:outline-none focus:shadow-outline"
					  type = "text"
					  title = "voterAddress"
					  placeholder = "Voter Address"
					  onChange={(e) => setVoterAddress(e.target.value)}  
				   />
                </div>
				   <div className="my-4 w-1/2 lg:w-1/4">
					<button 
					       className="uppercase text-sm font-bold tracking-wide bg-blue-900 text-gray-100 p-3 rounded-lg w-full 
                      focus:outline-none focus:shadow-outline"
					       onClick={whiteListAddress}
					>
                           Register Voter
                    </button>
				</div>
			</div>

            <div className="w-full p-4 my-4 md:px-12 lg:w-9/12 lg:pl-20 lg:pr-40 mr-auto rounded-2xl shadow-2xl">
			     <div className="flex">
				   <h1 className="font-bold text-2xl">Start Voting</h1>
			     </div>
				   <div className="my-4 w-1/2 lg:w-1/4">
					  <button className="uppercase text-sm font-bold tracking-wide bg-green-700 text-gray-100 p-3 rounded-lg w-full 
                      focus:outline-none focus:shadow-outline"
					          onClick={startVoting}
				 >
                        start voting
                      </button>
				   </div>
			     </div>

            <div className="w-full p-4 my-4 md:px-12 lg:w-9/12 lg:pl-20 lg:pr-40 mr-auto rounded-2xl shadow-2xl">
			    <div className="flex">
				    <h1 className="font-bold text-2xl">Stop Voting</h1>
			    </div>
				  <div className="my-4 w-1/2 lg:w-1/4">
					  <button className="uppercase text-sm font-bold tracking-wide bg-red-600 text-gray-100 p-3 rounded-lg w-full 
                      focus:outline-none focus:shadow-outline"
					           onClick={stopVoting}
				  >
                       stop voting
                  </button>
				</div>
			</div>

            <div className="w-full p-4 my-4 md:px-12 lg:w-9/12 lg:pl-20 lg:pr-40 mr-auto rounded-2xl shadow-2xl">
			   <div className="flex">
				   <h1 className="font-bold text-2xl">Pick Winner</h1>
			   </div>
			<div className="grid grid-cols-1 gap-5 md:grid-cols-2 mt-2">
				<input 
				     className ="w-full bg-gray-100 text-gray-900 mt-2 p-3 rounded-lg focus:outline-none focus:shadow-outline"
					 type = "text"
					 title = "winner"
					 placeholder = "Winner"
					 onChange={(e) => setWinnerr(e.target.value)}  
				/>
            </div>
				<div className="my-4 w-1/2 lg:w-1/4">
					<button className="uppercase text-sm font-bold tracking-wide bg-blue-900 text-gray-100 p-3 rounded-lg w-full 
                      focus:outline-none focus:shadow-outline"
					        onClick={winner}
					>
                      Pick Winner
                    </button>
				</div>
			</div>
      </div>
    </div>
  </main>
   </>
  )
}
